# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank
first_name: Naomi
last_name: Lubkin
email: naomil1732@gmail.com

description: The contents of work produced by Naomi Lubkin in the course Biology 420: Ocean Conservation 
and Sustainability at the University of British Columbia in Spring 2023.
keywords: ocean-sustainability, ocean-conservation, student, personal-website
lang: en
url: https://naomi-lubkin.github.io
last_updated: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
theme: jekyll-theme-dinky

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true

# Dimensions
max_width: 800px

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: naomi-lubkin
twitter_username: naomilubkin
contact_note: >
The easiest way to get in touch with me is via email (naomil1732@gmail.com)

